### ISSUE TITLE
Getting laurel.LaurelException: API authentication failed

### ISSUE THREAD

**Issue by hanlongwang** [mjg59/python-laurel#2]
Since GE switched to Cync

**Comment by lordlala** [comment]
Same here. This is what I'm seeing:

root@HomeAssistant:~/dimond/python-dimond# python3 test.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/laurel-0.5-py3.7.egg/laurel/__init__.py", line 31, in authenticate
    return (r.json()['access_token'], r.json()['user_id'])
KeyError: 'access_token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 2, in <module>
    connection = laurel.laurel("******@gmail.com","*******")
  File "/usr/local/lib/python3.7/dist-packages/laurel-0.5-py3.7.egg/laurel/__init__.py", line 90, in __init__
    (self.auth, self.userid) = authenticate(user, password)
  File "/usr/local/lib/python3.7/dist-packages/laurel-0.5-py3.7.egg/laurel/__init__.py", line 33, in authenticate
    raise(LaurelException('API authentication failed'))
laurel.LaurelException: API authentication failed
root@HomeAssistant:~/dimond/python-dimond#

**Comment by zimmra** [comment]
Looks like somebody has resolved [here](https://github.com/unixpickle/cbyge/blob/main/login_2fa/main.go)
Might try to convert to Python this weekend and see if I can get it to work

**Comment by wanderling** [comment]
They also added an email verification code recently FYI.

**Comment by KTibow** [comment]
@zimmra did you try?
