### ISSUE TITLE
Using my GE Cync username and password doesn't authenticate

### ISSUE THREAD

**Issue by aaronkbutler** [mjg59/python-laurel#5]
I am unable to authenticate. Keep getting this error:

`
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/laurel/__init__.py", line 31, in authenticate
    return (r.json()['access_token'], r.json()['user_id'])
KeyError: 'access_token'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/pi/test.py", line 3, in <module>
    devices = laurel.laurel("MYUSERNAMEHERE", "MYPASSWORDHERE")
  File "/home/pi/.local/lib/python3.9/site-packages/laurel/__init__.py", line 90, in __init__
    (self.auth, self.userid) = authenticate(user, password)
  File "/home/pi/.local/lib/python3.9/site-packages/laurel/__init__.py", line 33, in authenticate
    raise(LaurelException('API authentication failed'))
laurel.LaurelException: API authentication failed
`

**Comment by baudneo** [comment]
The API endpoint may have changed. I added a `print(f"{r.json() = }")` to the laurel \_\_init__.py and it returns a "user not found" response.

```
r.json() = {'error': {'msg': 'user not exists', 'code': 4041011}}
```

~~@mjg59 Do you have any idea on if this is the cause of the error?~~

It seems the API endpoints did change, I am working on updating the laurel Auth code for the newer 2FA cync accounts. This may not pan out but ill give it a go.
